
  language: "node_js",
  node_js:
    - 12
  cache:
  directories:
  - node_modules
  services:
    - postgresql
  before_script:
    - npm install
    - psql -c 'create database priceandpromotions;' -U student
    - npm run generateAll & npm seedPostgres
  script:
    - npm run test
  notifications:
    email: false