# version: '3.3'

# services:

#   redis:
#     image: redis
#     container_name: cache
#     ports:
#       - "6379:6379"
  
  app:
    # image: krispytrt/humble-price
    restart: always
    container_name: priceandpromotions
    build: .
    working_dir: /usr/src/priceandpromotions
    # links:
    #   - redis
    ports:
      - "3006:3006"
    env_file:
      - .env
    command: bash -c "npm run start"

